using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;
using TMPro;
using UnityEngine.UI;

public class m5_lessonUI : MonoBehaviour
{
    private NetworkGlobals netGlbScr;
    private Globals glbScr;
    [SerializeField] private TextMeshProUGUI m1lockText;
    [SerializeField] private TextMeshProUGUI m2lockText;
    [SerializeField] private TextMeshProUGUI m3lockText;
    [SerializeField] private TextMeshProUGUI m4lockText;
    [SerializeField] private TextMeshProUGUI m5lockText;
    [SerializeField] private TextMeshProUGUI m6lockText;
    [SerializeField] private TextMeshProUGUI m7lockText;
    [SerializeField] private TextMeshProUGUI m8lockText;
    [SerializeField] private TextMeshProUGUI m9lockText;
    [SerializeField] private TextMeshProUGUI m10lockText;
    [SerializeField] private TextMeshProUGUI m11lockText;
    [SerializeField] private TextMeshProUGUI m12lockText;
    [SerializeField] private TextMeshProUGUI m13lockText;
    [SerializeField] private TextMeshProUGUI m14lockText;
    [SerializeField] private TextMeshProUGUI m15lockText;
    [SerializeField] private TextMeshProUGUI m16lockText;
    [SerializeField] private TextMeshProUGUI m17lockText;
    [SerializeField] private TextMeshProUGUI m18lockText;
    [SerializeField] private TextMeshProUGUI m19lockText;
    [SerializeField] private TextMeshProUGUI m20lockText;
    [SerializeField] private TextMeshProUGUI m21lockText;
    [SerializeField] private TextMeshProUGUI m22lockText;
    [SerializeField] private TextMeshProUGUI m23lockText;
    [SerializeField] private TextMeshProUGUI m24lockText;
    [SerializeField] Button m1btn;
    [SerializeField] Button m2btn;
    [SerializeField] Button m3btn;
    [SerializeField] Button m4btn;
    [SerializeField] Button m5btn;
    [SerializeField] Button m6btn;
    [SerializeField] Button m7btn;
    [SerializeField] Button m8btn;
    [SerializeField] Button m9btn;
    [SerializeField] Button m10btn;
    [SerializeField] Button m11btn;
    [SerializeField] Button m12btn;
    [SerializeField] Button m13btn;
    [SerializeField] Button m14btn;
    [SerializeField] Button m15btn;
    [SerializeField] Button m16btn;
    [SerializeField] Button m17btn;
    [SerializeField] Button m18btn;
    [SerializeField] Button m19btn;
    [SerializeField] Button m20btn;
    [SerializeField] Button m21btn;
    [SerializeField] Button m22btn;
    [SerializeField] Button m23btn;
    [SerializeField] Button m24btn;
    [SerializeField] TextMeshProUGUI m1scoreText;
    [SerializeField] TextMeshProUGUI m2scoreText;
    [SerializeField] TextMeshProUGUI m3scoreText;
    [SerializeField] TextMeshProUGUI m4scoreText;
    [SerializeField] TextMeshProUGUI m5scoreText;
    [SerializeField] TextMeshProUGUI m6scoreText;
    [SerializeField] TextMeshProUGUI m7scoreText;
    [SerializeField] TextMeshProUGUI m8scoreText;
    [SerializeField] TextMeshProUGUI m9scoreText;
    [SerializeField] TextMeshProUGUI m10scoreText;
    [SerializeField] TextMeshProUGUI m11scoreText;
    [SerializeField] TextMeshProUGUI m12scoreText;
    [SerializeField] TextMeshProUGUI m13scoreText;
    [SerializeField] TextMeshProUGUI m14scoreText;
    [SerializeField] TextMeshProUGUI m15scoreText;
    [SerializeField] TextMeshProUGUI m16scoreText;
    [SerializeField] TextMeshProUGUI m17scoreText;
    [SerializeField] TextMeshProUGUI m18scoreText;
    [SerializeField] TextMeshProUGUI m19scoreText;
    [SerializeField] TextMeshProUGUI m20scoreText;
    [SerializeField] TextMeshProUGUI m21scoreText;
    [SerializeField] TextMeshProUGUI m22scoreText;
    [SerializeField] TextMeshProUGUI m23scoreText;
    [SerializeField] TextMeshProUGUI m24scoreText;

    private void Start()
    {
        netGlbScr = GameObject.Find("NetworkGlobals").GetComponent<NetworkGlobals>();
        glbScr = GameObject.Find("globals").GetComponent<Globals>();
        UnlockButtons();

        m1lockText.text = "Click to begin.";
        m2lockText.text = "Click to begin.";
        m3lockText.text = "Click to begin.";
        m4lockText.text = "Click to begin.";
        m5lockText.text = "Click to begin.";
        m6lockText.text = "Click to begin.";
        m7lockText.text = "Click to begin.";
        m8lockText.text = "Click to begin.";
        m9lockText.text = "Click to begin.";
        m10lockText.text = "Click to begin.";
        m11lockText.text = "Click to begin.";
        m12lockText.text = "Click to begin.";
        m13lockText.text = "Click to begin.";
        m14lockText.text = "Click to begin.";
        m15lockText.text = "Click to begin.";
        m16lockText.text = "Click to begin.";
        m17lockText.text = "Click to begin.";
        m18lockText.text = "Click to begin.";
        m19lockText.text = "Click to begin.";
        m20lockText.text = "Click to begin.";
        m21lockText.text = "Click to begin.";
        m22lockText.text = "Click to begin.";
        m23lockText.text = "Click to begin.";
        m24lockText.text = "Click to begin.";
        m1btn.interactable = true;
        m2btn.interactable = true;
        m3btn.interactable = true;
        m4btn.interactable = true;
        m5btn.interactable = true;
        m6btn.interactable = true;
        m7btn.interactable = true;
        m8btn.interactable = true;
        m9btn.interactable = true;
        m10btn.interactable = true;
        m11btn.interactable = true;
        m12btn.interactable = true;
        m13btn.interactable = true;
        m14btn.interactable = true;
        m15btn.interactable = true;
        m16btn.interactable = true;
        m17btn.interactable = true;
        m18btn.interactable = true;
        m19btn.interactable = true;
        m20btn.interactable = true;
        m21btn.interactable = true;
        m22btn.interactable = true;
        m23btn.interactable = true;
        m24btn.interactable = true;

        m1scoreText.text = "Test score " + glbScr.M5EQ_T1_Score + " out of 20";
        m2scoreText.text = "Test score " + glbScr.M5EQ_T2_Score + " out of 20";
        m3scoreText.text = "Test score " + glbScr.M5EQ_T3_Score + " out of 30";
        m4scoreText.text = "Test score " + glbScr.M5EQ_T4_Score + " out of 20";
        m5scoreText.text = "Test score " + glbScr.M5EQ_T5_Score + " out of 20";
        m6scoreText.text = "Test score " + glbScr.M5EQ_T6_Score + " out of 30";
        m7scoreText.text = "Test score " + glbScr.M5EQ_T7_Score + " out of 20";
        m8scoreText.text = "Test score " + glbScr.M5EQ_T8_Score + " out of 20";
        m9scoreText.text = "Test score " + glbScr.M5EQ_T9_Score + " out of 30";
        m10scoreText.text = "Test score " + glbScr.M5EQ_T10_Score + " out of 20";
        m11scoreText.text = "Test score " + glbScr.M5EQ_T11_Score + " out of 20";
        m12scoreText.text = "Test score " + glbScr.M5EQ_T12_Score + " out of 30";
        m13scoreText.text = "Test score " + glbScr.M5EQ_T13_Score + " out of 20";
        m14scoreText.text = "Test score " + glbScr.M5EQ_T14_Score + " out of 20";
        m15scoreText.text = "Test score " + glbScr.M5EQ_T15_Score + " out of 30";
        m16scoreText.text = "Test score " + glbScr.M5EQ_T16_Score + " out of 20";
        m17scoreText.text = "Test score " + glbScr.M5EQ_T17_Score + " out of 20";
        m18scoreText.text = "Test score " + glbScr.M5EQ_T18_Score + " out of 30";
        m19scoreText.text = "Test score " + glbScr.M5EQ_T19_Score + " out of 20";
        m20scoreText.text = "Test score " + glbScr.M5EQ_T20_Score + " out of 20";
        m21scoreText.text = "Test score " + glbScr.M5EQ_T21_Score + " out of 30";
        m22scoreText.text = "Test score " + glbScr.M5EQ_T22_Score + " out of 20";
        m23scoreText.text = "Test score " + glbScr.M5EQ_T23_Score + " out of 20";
        m24scoreText.text = "Test score " + glbScr.M5EQ_T24_Score + " out of 30";
    }

    void UnlockButtons()
    {
        if (glbScr.m5eq_passedTests == 0f)
        {
            m1lockText.text = "Click to begin.";
            m2lockText.text = "Locked";
            m3lockText.text = "Locked";
            m4lockText.text = "Locked";
            m5lockText.text = "Locked";
            m6lockText.text = "Locked";
            m7lockText.text = "Locked";
            m8lockText.text = "Locked";
            m9lockText.text = "Locked";
            m10lockText.text = "Locked";
            m11lockText.text = "Locked";
            m12lockText.text = "Locked";
            m13lockText.text = "Locked";
            m14lockText.text = "Locked";
            m15lockText.text = "Locked";
            m16lockText.text = "Locked";
            m17lockText.text = "Locked";
            m18lockText.text = "Locked";
            m19lockText.text = "Locked";
            m20lockText.text = "Locked";
            m21lockText.text = "Locked";
            m22lockText.text = "Locked";
            m23lockText.text = "Locked";
            m24lockText.text = "Locked";
            m1btn.interactable = true;
            m2btn.interactable = false;
            m3btn.interactable = false;
            m4btn.interactable = false;
            m5btn.interactable = false;
            m6btn.interactable = false;
            m7btn.interactable = false;
            m8btn.interactable = false;
            m9btn.interactable = false;
            m10btn.interactable = false;
            m11btn.interactable = false;
            m12btn.interactable = false;
            m13btn.interactable = false;
            m14btn.interactable = false;
            m15btn.interactable = false;
            m16btn.interactable = false;
            m17btn.interactable = false;
            m18btn.interactable = false;
            m19btn.interactable = false;
            m20btn.interactable = false;
            m21btn.interactable = false;
            m22btn.interactable = false;
            m23btn.interactable = false;
            m24btn.interactable = false;
        }
        else if (glbScr.m5eq_passedTests == 1f)
        {
            m1lockText.text = "Click to begin.";
            m2lockText.text = "Click to begin.";
            m3lockText.text = "Locked";
            m4lockText.text = "Locked";
            m5lockText.text = "Locked";
            m6lockText.text = "Locked";
            m7lockText.text = "Locked";
            m8lockText.text = "Locked";
            m9lockText.text = "Locked";
            m10lockText.text = "Locked";
            m11lockText.text = "Locked";
            m12lockText.text = "Locked";
            m13lockText.text = "Locked";
            m14lockText.text = "Locked";
            m15lockText.text = "Locked";
            m16lockText.text = "Locked";
            m17lockText.text = "Locked";
            m18lockText.text = "Locked";
            m19lockText.text = "Locked";
            m20lockText.text = "Locked";
            m21lockText.text = "Locked";
            m22lockText.text = "Locked";
            m23lockText.text = "Locked";
            m24lockText.text = "Locked";
            m1btn.interactable = true;
            m2btn.interactable = true;
            m3btn.interactable = false;
            m4btn.interactable = false;
            m5btn.interactable = false;
            m6btn.interactable = false;
            m7btn.interactable = false;
            m8btn.interactable = false;
            m9btn.interactable = false;
            m10btn.interactable = false;
            m11btn.interactable = false;
            m12btn.interactable = false;
            m13btn.interactable = false;
            m14btn.interactable = false;
            m15btn.interactable = false;
            m16btn.interactable = false;
            m17btn.interactable = false;
            m18btn.interactable = false;
            m19btn.interactable = false;
            m20btn.interactable = false;
            m21btn.interactable = false;
            m22btn.interactable = false;
            m23btn.interactable = false;
            m24btn.interactable = false;
        }
        else if (glbScr.m5eq_passedTests == 2f)
        {
            m1lockText.text = "Click to begin.";
            m2lockText.text = "Click to begin.";
            m3lockText.text = "Click to begin.";
            m4lockText.text = "Locked";
            m5lockText.text = "Locked";
            m6lockText.text = "Locked";
            m7lockText.text = "Locked";
            m8lockText.text = "Locked";
            m9lockText.text = "Locked";
            m10lockText.text = "Locked";
            m11lockText.text = "Locked";
            m12lockText.text = "Locked";
            m13lockText.text = "Locked";
            m14lockText.text = "Locked";
            m15lockText.text = "Locked";
            m16lockText.text = "Locked";
            m17lockText.text = "Locked";
            m18lockText.text = "Locked";
            m19lockText.text = "Locked";
            m20lockText.text = "Locked";
            m21lockText.text = "Locked";
            m22lockText.text = "Locked";
            m23lockText.text = "Locked";
            m24lockText.text = "Locked";
            m1btn.interactable = true;
            m2btn.interactable = true;
            m3btn.interactable = true;
            m4btn.interactable = false;
            m5btn.interactable = false;
            m6btn.interactable = false;
            m7btn.interactable = false;
            m8btn.interactable = false;
            m9btn.interactable = false;
            m10btn.interactable = false;
            m11btn.interactable = false;
            m12btn.interactable = false;
            m13btn.interactable = false;
            m14btn.interactable = false;
            m15btn.interactable = false;
            m16btn.interactable = false;
            m17btn.interactable = false;
            m18btn.interactable = false;
            m19btn.interactable = false;
            m20btn.interactable = false;
            m21btn.interactable = false;
            m22btn.interactable = false;
            m23btn.interactable = false;
            m24btn.interactable = false;
        }
        else if (glbScr.m5eq_passedTests == 3f)
        {
            m1lockText.text = "Click to begin.";
            m2lockText.text = "Click to begin.";
            m3lockText.text = "Click to begin.";
            m4lockText.text = "Click to begin.";
            m5lockText.text = "Locked";
            m6lockText.text = "Locked";
            m7lockText.text = "Locked";
            m8lockText.text = "Locked";
            m9lockText.text = "Locked";
            m10lockText.text = "Locked";
            m11lockText.text = "Locked";
            m12lockText.text = "Locked";
            m13lockText.text = "Locked";
            m14lockText.text = "Locked";
            m15lockText.text = "Locked";
            m16lockText.text = "Locked";
            m17lockText.text = "Locked";
            m18lockText.text = "Locked";
            m19lockText.text = "Locked";
            m20lockText.text = "Locked";
            m21lockText.text = "Locked";
            m22lockText.text = "Locked";
            m23lockText.text = "Locked";
            m24lockText.text = "Locked";
            m1btn.interactable = true;
            m2btn.interactable = true;
            m3btn.interactable = true;
            m4btn.interactable = true;
            m5btn.interactable = false;
            m6btn.interactable = false;
            m7btn.interactable = false;
            m8btn.interactable = false;
            m9btn.interactable = false;
            m10btn.interactable = false;
            m11btn.interactable = false;
            m12btn.interactable = false;
            m13btn.interactable = false;
            m14btn.interactable = false;
            m15btn.interactable = false;
            m16btn.interactable = false;
            m17btn.interactable = false;
            m18btn.interactable = false;
            m19btn.interactable = false;
            m20btn.interactable = false;
            m21btn.interactable = false;
            m22btn.interactable = false;
            m23btn.interactable = false;
            m24btn.interactable = false;
        }
        else if (glbScr.m5eq_passedTests == 4f)
        {
            m1lockText.text = "Click to begin.";
            m2lockText.text = "Click to begin.";
            m3lockText.text = "Click to begin.";
            m4lockText.text = "Click to begin.";
            m5lockText.text = "Click to begin.";
            m6lockText.text = "Locked";
            m7lockText.text = "Locked";
            m8lockText.text = "Locked";
            m9lockText.text = "Locked";
            m10lockText.text = "Locked";
            m11lockText.text = "Locked";
            m12lockText.text = "Locked";
            m13lockText.text = "Locked";
            m14lockText.text = "Locked";
            m15lockText.text = "Locked";
            m16lockText.text = "Locked";
            m17lockText.text = "Locked";
            m18lockText.text = "Locked";
            m19lockText.text = "Locked";
            m20lockText.text = "Locked";
            m21lockText.text = "Locked";
            m22lockText.text = "Locked";
            m23lockText.text = "Locked";
            m24lockText.text = "Locked";
            m1btn.interactable = true;
            m2btn.interactable = true;
            m3btn.interactable = true;
            m4btn.interactable = true;
            m5btn.interactable = true;
            m6btn.interactable = false;
            m7btn.interactable = false;
            m8btn.interactable = false;
            m9btn.interactable = false;
            m10btn.interactable = false;
            m11btn.interactable = false;
            m12btn.interactable = false;
            m13btn.interactable = false;
            m14btn.interactable = false;
            m15btn.interactable = false;
            m16btn.interactable = false;
            m17btn.interactable = false;
            m18btn.interactable = false;
            m19btn.interactable = false;
            m20btn.interactable = false;
            m21btn.interactable = false;
            m22btn.interactable = false;
            m23btn.interactable = false;
            m24btn.interactable = false;
        }
        else if (glbScr.m5eq_passedTests == 5f)
        {
            m1lockText.text = "Click to begin.";
            m2lockText.text = "Click to begin.";
            m3lockText.text = "Click to begin.";
            m4lockText.text = "Click to begin.";
            m5lockText.text = "Click to begin.";
            m6lockText.text = "Click to begin.";
            m7lockText.text = "Locked";
            m8lockText.text = "Locked";
            m9lockText.text = "Locked";
            m10lockText.text = "Locked";
            m11lockText.text = "Locked";
            m12lockText.text = "Locked";
            m13lockText.text = "Locked";
            m14lockText.text = "Locked";
            m15lockText.text = "Locked";
            m16lockText.text = "Locked";
            m17lockText.text = "Locked";
            m18lockText.text = "Locked";
            m19lockText.text = "Locked";
            m20lockText.text = "Locked";
            m21lockText.text = "Locked";
            m22lockText.text = "Locked";
            m23lockText.text = "Locked";
            m24lockText.text = "Locked";
            m1btn.interactable = true;
            m2btn.interactable = true;
            m3btn.interactable = true;
            m4btn.interactable = true;
            m5btn.interactable = true;
            m6btn.interactable = true;
            m7btn.interactable = false;
            m8btn.interactable = false;
            m9btn.interactable = false;
            m10btn.interactable = false;
            m11btn.interactable = false;
            m12btn.interactable = false;
            m13btn.interactable = false;
            m14btn.interactable = false;
            m15btn.interactable = false;
            m16btn.interactable = false;
            m17btn.interactable = false;
            m18btn.interactable = false;
            m19btn.interactable = false;
            m20btn.interactable = false;
            m21btn.interactable = false;
            m22btn.interactable = false;
            m23btn.interactable = false;
            m24btn.interactable = false;
        }
        else if (glbScr.m5eq_passedTests == 6f)
        {
            m1lockText.text = "Click to begin.";
            m2lockText.text = "Click to begin.";
            m3lockText.text = "Click to begin.";
            m4lockText.text = "Click to begin.";
            m5lockText.text = "Click to begin.";
            m6lockText.text = "Click to begin.";
            m7lockText.text = "Click to begin.";
            m8lockText.text = "Locked";
            m9lockText.text = "Locked";
            m10lockText.text = "Locked";
            m11lockText.text = "Locked";
            m12lockText.text = "Locked";
            m13lockText.text = "Locked";
            m14lockText.text = "Locked";
            m15lockText.text = "Locked";
            m16lockText.text = "Locked";
            m17lockText.text = "Locked";
            m18lockText.text = "Locked";
            m19lockText.text = "Locked";
            m20lockText.text = "Locked";
            m21lockText.text = "Locked";
            m22lockText.text = "Locked";
            m23lockText.text = "Locked";
            m24lockText.text = "Locked";
            m1btn.interactable = true;
            m2btn.interactable = true;
            m3btn.interactable = true;
            m4btn.interactable = true;
            m5btn.interactable = true;
            m6btn.interactable = true;
            m7btn.interactable = true;
            m8btn.interactable = false;
            m9btn.interactable = false;
            m10btn.interactable = false;
            m11btn.interactable = false;
            m12btn.interactable = false;
            m13btn.interactable = false;
            m14btn.interactable = false;
            m15btn.interactable = false;
            m16btn.interactable = false;
            m17btn.interactable = false;
            m18btn.interactable = false;
            m19btn.interactable = false;
            m20btn.interactable = false;
            m21btn.interactable = false;
            m22btn.interactable = false;
            m23btn.interactable = false;
            m24btn.interactable = false;
        }
        else if (glbScr.m5eq_passedTests == 7f)
        {
            m1lockText.text = "Click to begin.";
            m2lockText.text = "Click to begin.";
            m3lockText.text = "Click to begin.";
            m4lockText.text = "Click to begin.";
            m5lockText.text = "Click to begin.";
            m6lockText.text = "Click to begin.";
            m7lockText.text = "Click to begin.";
            m8lockText.text = "Click to begin.";
            m9lockText.text = "Locked";
            m10lockText.text = "Locked";
            m11lockText.text = "Locked";
            m12lockText.text = "Locked";
            m13lockText.text = "Locked";
            m14lockText.text = "Locked";
            m15lockText.text = "Locked";
            m16lockText.text = "Locked";
            m17lockText.text = "Locked";
            m18lockText.text = "Locked";
            m19lockText.text = "Locked";
            m20lockText.text = "Locked";
            m21lockText.text = "Locked";
            m22lockText.text = "Locked";
            m23lockText.text = "Locked";
            m24lockText.text = "Locked";
            m1btn.interactable = true;
            m2btn.interactable = true;
            m3btn.interactable = true;
            m4btn.interactable = true;
            m5btn.interactable = true;
            m6btn.interactable = true;
            m7btn.interactable = true;
            m8btn.interactable = true;
            m9btn.interactable = false;
            m10btn.interactable = false;
            m11btn.interactable = false;
            m12btn.interactable = false;
            m13btn.interactable = false;
            m14btn.interactable = false;
            m15btn.interactable = false;
            m16btn.interactable = false;
            m17btn.interactable = false;
            m18btn.interactable = false;
            m19btn.interactable = false;
            m20btn.interactable = false;
            m21btn.interactable = false;
            m22btn.interactable = false;
            m23btn.interactable = false;
            m24btn.interactable = false;
        }
        else if (glbScr.m5eq_passedTests == 8f)
        {
            m1lockText.text = "Click to begin.";
            m2lockText.text = "Click to begin.";
            m3lockText.text = "Click to begin.";
            m4lockText.text = "Click to begin.";
            m5lockText.text = "Click to begin.";
            m6lockText.text = "Click to begin.";
            m7lockText.text = "Click to begin.";
            m8lockText.text = "Click to begin.";
            m9lockText.text = "Click to begin.";
            m10lockText.text = "Locked";
            m11lockText.text = "Locked";
            m12lockText.text = "Locked";
            m13lockText.text = "Locked";
            m14lockText.text = "Locked";
            m15lockText.text = "Locked";
            m16lockText.text = "Locked";
            m17lockText.text = "Locked";
            m18lockText.text = "Locked";
            m19lockText.text = "Locked";
            m20lockText.text = "Locked";
            m21lockText.text = "Locked";
            m22lockText.text = "Locked";
            m23lockText.text = "Locked";
            m24lockText.text = "Locked";
            m1btn.interactable = true;
            m2btn.interactable = true;
            m3btn.interactable = true;
            m4btn.interactable = true;
            m5btn.interactable = true;
            m6btn.interactable = true;
            m7btn.interactable = true;
            m8btn.interactable = true;
            m9btn.interactable = true;
            m10btn.interactable = false;
            m11btn.interactable = false;
            m12btn.interactable = false;
            m13btn.interactable = false;
            m14btn.interactable = false;
            m15btn.interactable = false;
            m16btn.interactable = false;
            m17btn.interactable = false;
            m18btn.interactable = false;
            m19btn.interactable = false;
            m20btn.interactable = false;
            m21btn.interactable = false;
            m22btn.interactable = false;
            m23btn.interactable = false;
            m24btn.interactable = false;
        }
        else if (glbScr.m5eq_passedTests == 9f)
        {
            m1lockText.text = "Click to begin.";
            m2lockText.text = "Click to begin.";
            m3lockText.text = "Click to begin.";
            m4lockText.text = "Click to begin.";
            m5lockText.text = "Click to begin.";
            m6lockText.text = "Click to begin.";
            m7lockText.text = "Click to begin.";
            m8lockText.text = "Click to begin.";
            m9lockText.text = "Click to begin.";
            m10lockText.text = "Click to begin.";
            m11lockText.text = "Locked";
            m12lockText.text = "Locked";
            m13lockText.text = "Locked";
            m14lockText.text = "Locked";
            m15lockText.text = "Locked";
            m16lockText.text = "Locked";
            m17lockText.text = "Locked";
            m18lockText.text = "Locked";
            m19lockText.text = "Locked";
            m20lockText.text = "Locked";
            m21lockText.text = "Locked";
            m22lockText.text = "Locked";
            m23lockText.text = "Locked";
            m24lockText.text = "Locked";
            m1btn.interactable = true;
            m2btn.interactable = true;
            m3btn.interactable = true;
            m4btn.interactable = true;
            m5btn.interactable = true;
            m6btn.interactable = true;
            m7btn.interactable = true;
            m8btn.interactable = true;
            m9btn.interactable = true;
            m10btn.interactable = true;
            m11btn.interactable = false;
            m12btn.interactable = false;
            m13btn.interactable = false;
            m14btn.interactable = false;
            m15btn.interactable = false;
            m16btn.interactable = false;
            m17btn.interactable = false;
            m18btn.interactable = false;
            m19btn.interactable = false;
            m20btn.interactable = false;
            m21btn.interactable = false;
            m22btn.interactable = false;
            m23btn.interactable = false;
            m24btn.interactable = false;
        }
        else if (glbScr.m5eq_passedTests == 10f)
        {
            m1lockText.text = "Click to begin.";
            m2lockText.text = "Click to begin.";
            m3lockText.text = "Click to begin.";
            m4lockText.text = "Click to begin.";
            m5lockText.text = "Click to begin.";
            m6lockText.text = "Click to begin.";
            m7lockText.text = "Click to begin.";
            m8lockText.text = "Click to begin.";
            m9lockText.text = "Click to begin.";
            m10lockText.text = "Click to begin.";
            m11lockText.text = "Click to begin.";
            m12lockText.text = "Locked";
            m13lockText.text = "Locked";
            m14lockText.text = "Locked";
            m15lockText.text = "Locked";
            m16lockText.text = "Locked";
            m17lockText.text = "Locked";
            m18lockText.text = "Locked";
            m19lockText.text = "Locked";
            m20lockText.text = "Locked";
            m21lockText.text = "Locked";
            m22lockText.text = "Locked";
            m23lockText.text = "Locked";
            m24lockText.text = "Locked";
            m1btn.interactable = true;
            m2btn.interactable = true;
            m3btn.interactable = true;
            m4btn.interactable = true;
            m5btn.interactable = true;
            m6btn.interactable = true;
            m7btn.interactable = true;
            m8btn.interactable = true;
            m9btn.interactable = true;
            m10btn.interactable = true;
            m11btn.interactable = true;
            m12btn.interactable = false;
            m13btn.interactable = false;
            m14btn.interactable = false;
            m15btn.interactable = false;
            m16btn.interactable = false;
            m17btn.interactable = false;
            m18btn.interactable = false;
            m19btn.interactable = false;
            m20btn.interactable = false;
            m21btn.interactable = false;
            m22btn.interactable = false;
            m23btn.interactable = false;
            m24btn.interactable = false;
        }
        else if (glbScr.m5eq_passedTests == 11f)
        {
            m1lockText.text = "Click to begin.";
            m2lockText.text = "Click to begin.";
            m3lockText.text = "Click to begin.";
            m4lockText.text = "Click to begin.";
            m5lockText.text = "Click to begin.";
            m6lockText.text = "Click to begin.";
            m7lockText.text = "Click to begin.";
            m8lockText.text = "Click to begin.";
            m9lockText.text = "Click to begin.";
            m10lockText.text = "Click to begin.";
            m11lockText.text = "Click to begin.";
            m12lockText.text = "Click to begin.";
            m13lockText.text = "Locked";
            m14lockText.text = "Locked";
            m15lockText.text = "Locked";
            m16lockText.text = "Locked";
            m17lockText.text = "Locked";
            m18lockText.text = "Locked";
            m19lockText.text = "Locked";
            m20lockText.text = "Locked";
            m21lockText.text = "Locked";
            m22lockText.text = "Locked";
            m23lockText.text = "Locked";
            m24lockText.text = "Locked";
            m1btn.interactable = true;
            m2btn.interactable = true;
            m3btn.interactable = true;
            m4btn.interactable = true;
            m5btn.interactable = true;
            m6btn.interactable = true;
            m7btn.interactable = true;
            m8btn.interactable = true;
            m9btn.interactable = true;
            m10btn.interactable = true;
            m11btn.interactable = true;
            m12btn.interactable = true;
            m13btn.interactable = false;
            m14btn.interactable = false;
            m15btn.interactable = false;
            m16btn.interactable = false;
            m17btn.interactable = false;
            m18btn.interactable = false;
            m19btn.interactable = false;
            m20btn.interactable = false;
            m21btn.interactable = false;
            m22btn.interactable = false;
            m23btn.interactable = false;
            m24btn.interactable = false;
        }
        else if (glbScr.m5eq_passedTests == 12f)
        {
            m1lockText.text = "Click to begin.";
            m2lockText.text = "Click to begin.";
            m3lockText.text = "Click to begin.";
            m4lockText.text = "Click to begin.";
            m5lockText.text = "Click to begin.";
            m6lockText.text = "Click to begin.";
            m7lockText.text = "Click to begin.";
            m8lockText.text = "Click to begin.";
            m9lockText.text = "Click to begin.";
            m10lockText.text = "Click to begin.";
            m11lockText.text = "Click to begin.";
            m12lockText.text = "Click to begin.";
            m13lockText.text = "Click to begin.";
            m14lockText.text = "Locked";
            m15lockText.text = "Locked";
            m16lockText.text = "Locked";
            m17lockText.text = "Locked";
            m18lockText.text = "Locked";
            m19lockText.text = "Locked";
            m20lockText.text = "Locked";
            m21lockText.text = "Locked";
            m22lockText.text = "Locked";
            m23lockText.text = "Locked";
            m24lockText.text = "Locked";
            m1btn.interactable = true;
            m2btn.interactable = true;
            m3btn.interactable = true;
            m4btn.interactable = true;
            m5btn.interactable = true;
            m6btn.interactable = true;
            m7btn.interactable = true;
            m8btn.interactable = true;
            m9btn.interactable = true;
            m10btn.interactable = true;
            m11btn.interactable = true;
            m12btn.interactable = true;
            m13btn.interactable = true;
            m14btn.interactable = false;
            m15btn.interactable = false;
            m16btn.interactable = false;
            m17btn.interactable = false;
            m18btn.interactable = false;
            m19btn.interactable = false;
            m20btn.interactable = false;
            m21btn.interactable = false;
            m22btn.interactable = false;
            m23btn.interactable = false;
            m24btn.interactable = false;
        }
        else if (glbScr.m5eq_passedTests == 13f)
        {
            m1lockText.text = "Click to begin.";
            m2lockText.text = "Click to begin.";
            m3lockText.text = "Click to begin.";
            m4lockText.text = "Click to begin.";
            m5lockText.text = "Click to begin.";
            m6lockText.text = "Click to begin.";
            m7lockText.text = "Click to begin.";
            m8lockText.text = "Click to begin.";
            m9lockText.text = "Click to begin.";
            m10lockText.text = "Click to begin.";
            m11lockText.text = "Click to begin.";
            m12lockText.text = "Click to begin.";
            m13lockText.text = "Click to begin.";
            m14lockText.text = "Click to begin.";
            m15lockText.text = "Locked";
            m16lockText.text = "Locked";
            m17lockText.text = "Locked";
            m18lockText.text = "Locked";
            m19lockText.text = "Locked";
            m20lockText.text = "Locked";
            m21lockText.text = "Locked";
            m22lockText.text = "Locked";
            m23lockText.text = "Locked";
            m24lockText.text = "Locked";
            m1btn.interactable = true;
            m2btn.interactable = true;
            m3btn.interactable = true;
            m4btn.interactable = true;
            m5btn.interactable = true;
            m6btn.interactable = true;
            m7btn.interactable = true;
            m8btn.interactable = true;
            m9btn.interactable = true;
            m10btn.interactable = true;
            m11btn.interactable = true;
            m12btn.interactable = true;
            m13btn.interactable = true;
            m14btn.interactable = true;
            m15btn.interactable = false;
            m16btn.interactable = false;
            m17btn.interactable = false;
            m18btn.interactable = false;
            m19btn.interactable = false;
            m20btn.interactable = false;
            m21btn.interactable = false;
            m22btn.interactable = false;
            m23btn.interactable = false;
            m24btn.interactable = false;
        }
        else if (glbScr.m5eq_passedTests == 14f)
        {
            m1lockText.text = "Click to begin.";
            m2lockText.text = "Click to begin.";
            m3lockText.text = "Click to begin.";
            m4lockText.text = "Click to begin.";
            m5lockText.text = "Click to begin.";
            m6lockText.text = "Click to begin.";
            m7lockText.text = "Click to begin.";
            m8lockText.text = "Click to begin.";
            m9lockText.text = "Click to begin.";
            m10lockText.text = "Click to begin.";
            m11lockText.text = "Click to begin.";
            m12lockText.text = "Click to begin.";
            m13lockText.text = "Click to begin.";
            m14lockText.text = "Click to begin.";
            m15lockText.text = "Click to begin.";
            m16lockText.text = "Locked";
            m17lockText.text = "Locked";
            m18lockText.text = "Locked";
            m19lockText.text = "Locked";
            m20lockText.text = "Locked";
            m21lockText.text = "Locked";
            m22lockText.text = "Locked";
            m23lockText.text = "Locked";
            m24lockText.text = "Locked";
            m1btn.interactable = true;
            m2btn.interactable = true;
            m3btn.interactable = true;
            m4btn.interactable = true;
            m5btn.interactable = true;
            m6btn.interactable = true;
            m7btn.interactable = true;
            m8btn.interactable = true;
            m9btn.interactable = true;
            m10btn.interactable = true;
            m11btn.interactable = true;
            m12btn.interactable = true;
            m13btn.interactable = true;
            m14btn.interactable = true;
            m15btn.interactable = true;
            m16btn.interactable = false;
            m17btn.interactable = false;
            m18btn.interactable = false;
            m19btn.interactable = false;
            m20btn.interactable = false;
            m21btn.interactable = false;
            m22btn.interactable = false;
            m23btn.interactable = false;
            m24btn.interactable = false;
        }
        else if (glbScr.m5eq_passedTests == 15f)
        {
            m1lockText.text = "Click to begin.";
            m2lockText.text = "Click to begin.";
            m3lockText.text = "Click to begin.";
            m4lockText.text = "Click to begin.";
            m5lockText.text = "Click to begin.";
            m6lockText.text = "Click to begin.";
            m7lockText.text = "Click to begin.";
            m8lockText.text = "Click to begin.";
            m9lockText.text = "Click to begin.";
            m10lockText.text = "Click to begin.";
            m11lockText.text = "Click to begin.";
            m12lockText.text = "Click to begin.";
            m13lockText.text = "Click to begin.";
            m14lockText.text = "Click to begin.";
            m15lockText.text = "Click to begin.";
            m16lockText.text = "Click to begin.";
            m17lockText.text = "Locked";
            m18lockText.text = "Locked";
            m19lockText.text = "Locked";
            m20lockText.text = "Locked";
            m21lockText.text = "Locked";
            m22lockText.text = "Locked";
            m23lockText.text = "Locked";
            m24lockText.text = "Locked";
            m1btn.interactable = true;
            m2btn.interactable = true;
            m3btn.interactable = true;
            m4btn.interactable = true;
            m5btn.interactable = true;
            m6btn.interactable = true;
            m7btn.interactable = false;
            m8btn.interactable = false;
            m9btn.interactable = false;
            m10btn.interactable = true;
            m11btn.interactable = true;
            m12btn.interactable = true;
            m13btn.interactable = true;
            m14btn.interactable = true;
            m15btn.interactable = true;
            m16btn.interactable = true;
            m17btn.interactable = false;
            m18btn.interactable = false;
            m19btn.interactable = false;
            m20btn.interactable = false;
            m21btn.interactable = false;
            m22btn.interactable = false;
            m23btn.interactable = false;
            m24btn.interactable = false;
        }
        else if (glbScr.m5eq_passedTests == 16f)
        {
            m1lockText.text = "Click to begin.";
            m2lockText.text = "Click to begin.";
            m3lockText.text = "Click to begin.";
            m4lockText.text = "Click to begin.";
            m5lockText.text = "Click to begin.";
            m6lockText.text = "Click to begin.";
            m7lockText.text = "Click to begin.";
            m8lockText.text = "Click to begin.";
            m9lockText.text = "Click to begin.";
            m10lockText.text = "Click to begin.";
            m11lockText.text = "Click to begin.";
            m12lockText.text = "Click to begin.";
            m13lockText.text = "Click to begin.";
            m14lockText.text = "Click to begin.";
            m15lockText.text = "Click to begin.";
            m16lockText.text = "Click to begin.";
            m17lockText.text = "Click to begin.";
            m18lockText.text = "Locked";
            m19lockText.text = "Locked";
            m20lockText.text = "Locked";
            m21lockText.text = "Locked";
            m22lockText.text = "Locked";
            m23lockText.text = "Locked";
            m24lockText.text = "Locked";
            m1btn.interactable = true;
            m2btn.interactable = true;
            m3btn.interactable = true;
            m4btn.interactable = true;
            m5btn.interactable = true;
            m6btn.interactable = true;
            m7btn.interactable = true;
            m8btn.interactable = true;
            m9btn.interactable = true;
            m10btn.interactable = true;
            m11btn.interactable = true;
            m12btn.interactable = true;
            m13btn.interactable = true;
            m14btn.interactable = true;
            m15btn.interactable = true;
            m16btn.interactable = true;
            m17btn.interactable = true;
            m18btn.interactable = false;
            m19btn.interactable = false;
            m20btn.interactable = false;
            m21btn.interactable = false;
            m22btn.interactable = false;
            m23btn.interactable = false;
            m24btn.interactable = false;
        }
        else if (glbScr.m5eq_passedTests == 17)
        {
            m1lockText.text = "Click to begin.";
            m2lockText.text = "Click to begin.";
            m3lockText.text = "Click to begin.";
            m4lockText.text = "Click to begin.";
            m5lockText.text = "Click to begin.";
            m6lockText.text = "Click to begin.";
            m7lockText.text = "Click to begin.";
            m8lockText.text = "Click to begin.";
            m9lockText.text = "Click to begin.";
            m10lockText.text = "Click to begin.";
            m11lockText.text = "Click to begin.";
            m12lockText.text = "Click to begin.";
            m13lockText.text = "Click to begin.";
            m14lockText.text = "Click to begin.";
            m15lockText.text = "Click to begin.";
            m16lockText.text = "Click to begin.";
            m17lockText.text = "Click to begin.";
            m18lockText.text = "Click to begin.";
            m19lockText.text = "Locked";
            m20lockText.text = "Locked";
            m21lockText.text = "Locked";
            m22lockText.text = "Locked";
            m23lockText.text = "Locked";
            m24lockText.text = "Locked";
            m1btn.interactable = true;
            m2btn.interactable = true;
            m3btn.interactable = true;
            m4btn.interactable = true;
            m5btn.interactable = true;
            m6btn.interactable = true;
            m7btn.interactable = true;
            m8btn.interactable = true;
            m9btn.interactable = true;
            m10btn.interactable = true;
            m11btn.interactable = true;
            m12btn.interactable = true;
            m13btn.interactable = true;
            m14btn.interactable = true;
            m15btn.interactable = true;
            m16btn.interactable = true;
            m17btn.interactable = true;
            m18btn.interactable = true;
            m19btn.interactable = false;
            m20btn.interactable = false;
            m21btn.interactable = false;
            m22btn.interactable = false;
            m23btn.interactable = false;
            m24btn.interactable = false;
        }
        else if (glbScr.m5eq_passedTests == 18f)
        {
            m1lockText.text = "Click to begin.";
            m2lockText.text = "Click to begin.";
            m3lockText.text = "Click to begin.";
            m4lockText.text = "Click to begin.";
            m5lockText.text = "Click to begin.";
            m6lockText.text = "Click to begin.";
            m7lockText.text = "Click to begin.";
            m8lockText.text = "Click to begin.";
            m9lockText.text = "Click to begin.";
            m10lockText.text = "Click to begin.";
            m11lockText.text = "Click to begin.";
            m12lockText.text = "Click to begin.";
            m13lockText.text = "Click to begin.";
            m14lockText.text = "Click to begin.";
            m15lockText.text = "Click to begin.";
            m16lockText.text = "Click to begin.";
            m17lockText.text = "Click to begin.";
            m18lockText.text = "Click to begin.";
            m19lockText.text = "Click to begin.";
            m20lockText.text = "Locked";
            m21lockText.text = "Locked";
            m22lockText.text = "Locked";
            m23lockText.text = "Locked";
            m24lockText.text = "Locked";
            m1btn.interactable = true;
            m2btn.interactable = true;
            m3btn.interactable = true;
            m4btn.interactable = true;
            m5btn.interactable = true;
            m6btn.interactable = true;
            m7btn.interactable = true;
            m8btn.interactable = true;
            m9btn.interactable = true;
            m10btn.interactable = true;
            m11btn.interactable = true;
            m12btn.interactable = true;
            m13btn.interactable = true;
            m14btn.interactable = true;
            m15btn.interactable = true;
            m16btn.interactable = true;
            m17btn.interactable = true;
            m18btn.interactable = true;
            m19btn.interactable = true;
            m20btn.interactable = false;
            m21btn.interactable = false;
            m22btn.interactable = false;
            m23btn.interactable = false;
            m24btn.interactable = false;
        }
        else if (glbScr.m5eq_passedTests == 19f)
        {
            m1lockText.text = "Click to begin.";
            m2lockText.text = "Click to begin.";
            m3lockText.text = "Click to begin.";
            m4lockText.text = "Click to begin.";
            m5lockText.text = "Click to begin.";
            m6lockText.text = "Click to begin.";
            m7lockText.text = "Click to begin.";
            m8lockText.text = "Click to begin.";
            m9lockText.text = "Click to begin.";
            m10lockText.text = "Click to begin.";
            m11lockText.text = "Click to begin.";
            m12lockText.text = "Click to begin.";
            m13lockText.text = "Click to begin.";
            m14lockText.text = "Click to begin.";
            m15lockText.text = "Click to begin.";
            m16lockText.text = "Click to begin.";
            m17lockText.text = "Click to begin.";
            m18lockText.text = "Click to begin.";
            m19lockText.text = "Click to begin.";
            m20lockText.text = "Click to begin.";
            m21lockText.text = "Locked";
            m22lockText.text = "Locked";
            m23lockText.text = "Locked";
            m24lockText.text = "Locked";
            m1btn.interactable = true;
            m2btn.interactable = true;
            m3btn.interactable = true;
            m4btn.interactable = true;
            m5btn.interactable = true;
            m6btn.interactable = true;
            m7btn.interactable = true;
            m8btn.interactable = true;
            m9btn.interactable = true;
            m10btn.interactable = true;
            m11btn.interactable = true;
            m12btn.interactable = true;
            m13btn.interactable = true;
            m14btn.interactable = true;
            m15btn.interactable = true;
            m16btn.interactable = true;
            m17btn.interactable = true;
            m18btn.interactable = true;
            m19btn.interactable = true;
            m20btn.interactable = true;
            m21btn.interactable = false;
            m22btn.interactable = false;
            m23btn.interactable = false;
            m24btn.interactable = false;
        }
        else if (glbScr.m5eq_passedTests == 20f)
        {
            m1lockText.text = "Click to begin.";
            m2lockText.text = "Click to begin.";
            m3lockText.text = "Click to begin.";
            m4lockText.text = "Click to begin.";
            m5lockText.text = "Click to begin.";
            m6lockText.text = "Click to begin.";
            m7lockText.text = "Click to begin.";
            m8lockText.text = "Click to begin.";
            m9lockText.text = "Click to begin.";
            m10lockText.text = "Click to begin.";
            m11lockText.text = "Click to begin.";
            m12lockText.text = "Click to begin.";
            m13lockText.text = "Click to begin.";
            m14lockText.text = "Click to begin.";
            m15lockText.text = "Click to begin.";
            m16lockText.text = "Click to begin.";
            m17lockText.text = "Click to begin.";
            m18lockText.text = "Click to begin.";
            m19lockText.text = "Click to begin.";
            m20lockText.text = "Click to begin.";
            m21lockText.text = "Click to begin.";
            m22lockText.text = "Locked";
            m23lockText.text = "Locked";
            m24lockText.text = "Locked";
            m1btn.interactable = true;
            m2btn.interactable = true;
            m3btn.interactable = true;
            m4btn.interactable = true;
            m5btn.interactable = true;
            m6btn.interactable = true;
            m7btn.interactable = true;
            m8btn.interactable = true;
            m9btn.interactable = true;
            m10btn.interactable = true;
            m11btn.interactable = true;
            m12btn.interactable = true;
            m13btn.interactable = true;
            m14btn.interactable = true;
            m15btn.interactable = true;
            m16btn.interactable = true;
            m17btn.interactable = true;
            m18btn.interactable = true;
            m19btn.interactable = true;
            m20btn.interactable = true;
            m21btn.interactable = true;
            m22btn.interactable = false;
            m23btn.interactable = false;
            m24btn.interactable = false;
        }
        else if (glbScr.m5eq_passedTests == 21f)
        {
            m1lockText.text = "Click to begin.";
            m2lockText.text = "Click to begin.";
            m3lockText.text = "Click to begin.";
            m4lockText.text = "Click to begin.";
            m5lockText.text = "Click to begin.";
            m6lockText.text = "Click to begin.";
            m7lockText.text = "Click to begin.";
            m8lockText.text = "Click to begin.";
            m9lockText.text = "Click to begin.";
            m10lockText.text = "Click to begin.";
            m11lockText.text = "Click to begin.";
            m12lockText.text = "Click to begin.";
            m13lockText.text = "Click to begin.";
            m14lockText.text = "Click to begin.";
            m15lockText.text = "Click to begin.";
            m16lockText.text = "Click to begin.";
            m17lockText.text = "Click to begin.";
            m18lockText.text = "Click to begin.";
            m19lockText.text = "Click to begin.";
            m20lockText.text = "Click to begin.";
            m21lockText.text = "Click to begin.";
            m22lockText.text = "Click to begin.";
            m23lockText.text = "Locked";
            m24lockText.text = "Locked";
            m1btn.interactable = true;
            m2btn.interactable = true;
            m3btn.interactable = true;
            m4btn.interactable = true;
            m5btn.interactable = true;
            m6btn.interactable = true;
            m7btn.interactable = true;
            m8btn.interactable = true;
            m9btn.interactable = true;
            m10btn.interactable = true;
            m11btn.interactable = true;
            m12btn.interactable = true;
            m13btn.interactable = true;
            m14btn.interactable = true;
            m15btn.interactable = true;
            m16btn.interactable = true;
            m17btn.interactable = true;
            m18btn.interactable = true;
            m19btn.interactable = true;
            m20btn.interactable = true;
            m21btn.interactable = true;
            m22btn.interactable = true;
            m23btn.interactable = false;
            m24btn.interactable = false;
        }
        else if (glbScr.m5eq_passedTests == 22f)
        {
            m1lockText.text = "Click to begin.";
            m2lockText.text = "Click to begin.";
            m3lockText.text = "Click to begin.";
            m4lockText.text = "Click to begin.";
            m5lockText.text = "Click to begin.";
            m6lockText.text = "Click to begin.";
            m7lockText.text = "Click to begin.";
            m8lockText.text = "Click to begin.";
            m9lockText.text = "Click to begin.";
            m10lockText.text = "Click to begin.";
            m11lockText.text = "Click to begin.";
            m12lockText.text = "Click to begin.";
            m13lockText.text = "Click to begin.";
            m14lockText.text = "Click to begin.";
            m15lockText.text = "Click to begin.";
            m16lockText.text = "Click to begin.";
            m17lockText.text = "Click to begin.";
            m18lockText.text = "Click to begin.";
            m19lockText.text = "Click to begin.";
            m20lockText.text = "Click to begin.";
            m21lockText.text = "LoClick to begin.cked";
            m22lockText.text = "Click to begin.";
            m23lockText.text = "Click to begin.";
            m24lockText.text = "Locked";
            m1btn.interactable = true;
            m2btn.interactable = true;
            m3btn.interactable = true;
            m4btn.interactable = true;
            m5btn.interactable = true;
            m6btn.interactable = true;
            m7btn.interactable = true;
            m8btn.interactable = true;
            m9btn.interactable = true;
            m10btn.interactable = true;
            m11btn.interactable = true;
            m12btn.interactable = true;
            m13btn.interactable = true;
            m14btn.interactable = true;
            m15btn.interactable = true;
            m16btn.interactable = true;
            m17btn.interactable = true;
            m18btn.interactable = true;
            m19btn.interactable = true;
            m20btn.interactable = true;
            m21btn.interactable = true;
            m22btn.interactable = true;
            m23btn.interactable = true;
            m24btn.interactable = false;
        }
        else if (glbScr.m5eq_passedTests >= 23f)
        {
            m1lockText.text = "Click to begin.";
            m2lockText.text = "Click to begin.";
            m3lockText.text = "Click to begin.";
            m4lockText.text = "Click to begin.";
            m5lockText.text = "Click to begin.";
            m6lockText.text = "Click to begin.";
            m7lockText.text = "Click to begin.";
            m8lockText.text = "Click to begin.";
            m9lockText.text = "Click to begin.";
            m10lockText.text = "Click to begin.";
            m11lockText.text = "Click to begin.";
            m12lockText.text = "Click to begin.";
            m13lockText.text = "Click to begin.";
            m14lockText.text = "Click to begin.";
            m15lockText.text = "Click to begin.";
            m16lockText.text = "Click to begin.";
            m17lockText.text = "Click to begin.";
            m18lockText.text = "Click to begin.";
            m19lockText.text = "Click to begin.";
            m20lockText.text = "Click to begin.";
            m21lockText.text = "Click to begin.";
            m22lockText.text = "Click to begin.";
            m23lockText.text = "Click to begin.";
            m24lockText.text = "Click to begin.";
            m1btn.interactable = true;
            m2btn.interactable = true;
            m3btn.interactable = true;
            m4btn.interactable = true;
            m5btn.interactable = true;
            m6btn.interactable = true;
            m7btn.interactable = true;
            m8btn.interactable = true;
            m9btn.interactable = true;
            m10btn.interactable = true;
            m11btn.interactable = true;
            m12btn.interactable = true;
            m13btn.interactable = true;
            m14btn.interactable = true;
            m15btn.interactable = true;
            m16btn.interactable = true;
            m17btn.interactable = true;
            m18btn.interactable = true;
            m19btn.interactable = true;
            m20btn.interactable = true;
            m21btn.interactable = true;
            m22btn.interactable = true;
            m23btn.interactable = true;
            m24btn.interactable = true;
        }
    }
}
